let LargeRegistrationFormPage = {
    registrationForm: '.registration',
    authoritySelect: '.wp > .multiselect',
    regionSelect: '.sb > .select-box > .multiselect',
    authorizeName: '#govermentNameOfRussiaSubject',
    workPlaceName: '#employeer',
    postName: '#presentPost',
    loadReference: '.ce',
    loadLaborBook: '.cwb',
    lastName: '#lastName',
    firstName: '#firstName',
    middleName: '#middleName',
    fullNameDative: '#fullNameDative',
    workEmail: '#workEmail',
    calendarInputs: "//input[@class='datepicker__input']",
    snilsInput: '.sn > .input',
    genderSelect: '.personal > .select-box > .multiselect',
    phone: '.phone-wrapper > .form > .input',
    personalPhoto: '.personal > .input-file',
    phoneApproveBtn: '.phone-approve',
    deliveryWaysList: '.delivery > .select-box > .multiselect',
    documentsList: '.passport-data > .select-box > .multiselect',
    passportSeries: '.psn > .input',
    passportNumber: '.pn > .input',
    passportIssuedBy: '#passportIssuedBy',
    passportCodeIssue: '.pcpidc > .form > .input',
    passport: '.pcpidc',
    placeOfBirth: '#placeOfBirth',
    isLastNameChangedCheckbox: '#isLastNameChanged',
    passportPhotoFile: '.ppwp',
    passportRegisterFile: '.ppwr ',
    changeNameFile: '.clnf',
    educationLevelList: '.education-document > .select-box > .multiselect',
    educationDocumentSerial: '#educationDocumentSerial',
    educationDocumentNumber: '#educationDocumentNumber',
    educationDocumentRegNumber: '#educationDocumentRegistrationNumber',
    educationDocumentFile: '.education-document > .input-file ',
    educationEndDate: '//div[contains(@class, "education-document")]',
    getAdditionalData: '.registration__section-caption',
    isEducationInProgressCheckbox: '#isEducationInProgress',
    isEducationInProgressVisibleStyledCheckbox: '.eip > .checkbox-label > .check',
    additionalEducationSelect: '.additional__education > .select-box > .multiselect',
    isGraduateStudentInProgressCheckbox: '#isGraduateStudentInProgress',
    isDisabledPeopleCheckbox: '#isDisabledPeople',
    dataHandleAcceptCheckbox: '#acceptRules',
    //terms of use is used from Small form
    //added to the path of images inputs and images added
    addedFileDisplay: '.input-file__attachment',
    fileInput: ' > .file > .file__input',
    inputContent: '> .input-content',
    submitBtn: '.btn',
    birthDay: '.personal',
    education: '.education-document',
    passportDelivery: '.pcpidc',
    additionalEducation: '.additional__education',
    postIndex: '#postIndex',
    postCity: '#postCity',
    postStreet: '#postStreet',
    postHouse: '.dph > #postHouse',
    postBuilding: '.form pdc > #postHouse',
    postAppartment: '#postApartment',
    deliveryAcceptCheckbox: '#deliveryAccept',
    nameChanges: '.clnf',
    changedLastName: '#educationDocumentLastName',
    changedFirstName: '#educationDocumentFirstName',
    changedMiddleName: '#educationDocumentMiddleName',
    additionalEducationEndDate: '.cee',
    magisterEndDate: '.gd',
    personalForm: '//div[contains(@class, "personal")]',
    passportDataForm: '//div[contains(@class, "passport-data")]',
    educationDocForm: '//div[contains(@class, "education-document")]',
    additionalEducationInProgressForm: '//div[contains(@class, "additional__education")]',
    magisterForm: '//div[contains(@class, "gd")]',
    registrationAddress: '#registrationAddress',
    avatarPhoto: '#photo'
};
export default LargeRegistrationFormPage;
